
export const metadata = {
  title: "Wedding -AdminPanel",
  description: "Generated by <Tamzid/>",
};


const dp = () => {
  return (
    <div>
       <h1>AdminPanel</h1>
    </div>
  );
}

export default dp ;