export const metadata = {
  title: "Wedding - UnderConstruction ",
  description: "Generated by <Tamzid/>",
};

import React from "react";
import Image from "next/image";
import logo from "@/app/assests/icons/under-construction.gif";
import Link from "next/link";

const underConstruction = () => {
  return (
    <div className="h-screen flex justify-center items-center">
      <div
        style={{ fontFamily: "Mooli, sans-serif" }}
        className="text-center bg-white"
      >
        <h1 style={{ fontFamily: "Young Serif, serif" }} className="text-4xl">
          Site Under Construction
        </h1>
        <div className=" flex justify-center ">
          <Image
            className="w-[300px] h-[300px] bg-gray-300"
            src={logo}
            alt=""
          />
        </div>
        <p className="mb-3 text-xl">Please forgive the inconvenience.</p>
        <p className="mb-1 text-md">We are currently initializing our site.</p>
        {/* eslint-disable-next-line react/no-unescaped-entities  */}
        <p>It's okay, we're excited too!</p>
        <Link
          href="/"
          className="inline-block mt-5 px-8 py-3 text-base font-semibold text-center text-black transition rounded-lg hover:bg-indigo-700 hover:text-white hover:shadow-gray-500
                 shadow-md shadow-gray-900"
        >
          Go to Home
        </Link>
      </div>
    </div>
  );
};

export default underConstruction;
